# Generated by Django 3.0.6 on 2020-05-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
